
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.yang.demo2.entity

spring:
  datasource:
    username: root
    password: 237502
    url: jdbc:mysql://localhost:3306/xjkk_tpgx?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver